BePartner_App_Mid/Controllers/S_AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.IO;
using System.Web.Security;
using BePartner_App_Mid.Models;
using BePartner_App_Mid.EF;
using static System.Net.WebRequestMethods;



namespace BePartner_App_Mid.Controllers
{
    public class S_AdminController : Controller
    {
        // GET: S_Admin
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Regstration_S1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Regstration_S1(S_Admin_Model_Reg01 SAMR1)
        {
            if (ModelState.IsValid)
            {
                Session["FirstName"] = SAMR1.FirstName;
                Session["LastName"] = SAMR1.LastName;
                Session["Email"] = SAMR1.Email;
                Session["Phone"] = SAMR1.Phone;
                Session["Gender"] = SAMR1.Gender;
                Session["NID"] = SAMR1.NID;
                Session["Address"] = SAMR1.Address;
                
              
                return RedirectToAction("Regstration_S2");

            }
            else
            {
               // ViewBag.Message = "Not Valid!!";

            }
            return View();
        }

        [HttpGet]
        public ActionResult Regstration_S2()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Regstration_S2(S_Admin_Model_Reg02 SAMR2)
        {
            if (ModelState.IsValid)
            {

                Session["DOB"] = SAMR2.DOB.ToString();
                Session["Security_key"] = SAMR2.Security_key;
                Session["Password"] = SAMR2.Password;
                Session["ConfirmPassword"] = SAMR2.ConfirmPassword;
                if (SAMR2.IMG_file != null)
                {
                    string path = Server.MapPath("~/Img/ADMIN");
                    string fileName = Path.GetFileName(SAMR2.IMG_file.FileName);
                    string fullpath = Path.Combine(path, fileName);
                    SAMR2.IMG_file.SaveAs(fullpath);  //save into img folder


                    // for data base
                    string databaseImgpath = "~/Img/ADMIN/" + fileName; 
                    Session["IMG_file"] = databaseImgpath;

                }

                


                var SAMR1 = new S_Admin_Model_Reg01();
                if (this.RegistrationCreate( SAMR1 , SAMR2))
                {
                    return RedirectToAction("login_S");


                    // ViewBag.Message = "Data Inserted!!";
                }
                else
                {
                    // ViewBag.Message = "Something went wrong!!";
                }
            }
            else
            {
                // ViewBag.Message = "not valid";
            }
            return View();
        }



        public bool RegistrationCreate(S_Admin_Model_Reg01 SAM1 , S_Admin_Model_Reg02 SAM2)
        {

            var admin = new Admin()
            {
                Ad_Email=Session["Email"].ToString(),
                FirstName=Session["FirstName"].ToString(),
                LastName=Session["LastName"].ToString(),
                Address=Session["Address"].ToString(),
                Phone=Session["Phone"].ToString(),
                Security_key=Session["Security_key"].ToString(),
                Gender=Session["Gender"].ToString(),
                Nid=Session["NID"].ToString(),
                Password=Session["Password"].ToString(),
                Img=Session["IMG_file"].ToString(),
                Dob = DateTime.Parse(Session["DOB"].ToString())

            };
            var db = new bePartnerCentralDatabaseEntities2();
            db.Admins.Add(admin);
            try
            {
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }

        }

        [HttpGet]
        public ActionResult login_S()
        {
            return View();
        }

        [HttpPost]
        public ActionResult login_S(S_Admin_model_login SAML, string ReturnUrl)
        {

            var db = new bePartnerCentralDatabaseEntities2();
            var ad = (from Id in db.Admins where Id.Ad_Email.Equals(SAML.Email) select Id).FirstOrDefault();
            
            if (ad != null)
            {
                if (ad.Password.Equals(SAML.Password))
                {
                    FormsAuthentication.SetAuthCookie(SAML.Email, true);
                    Session.RemoveAll();
                    Session["Email"] = SAML.Email;
                    HttpCookie c1 = new HttpCookie("ADInfo");
                    c1.Value = ad.Ad_Email.ToString();
                    c1.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(c1);
                    if (ReturnUrl != null)
                    {
                        string[] arr = ReturnUrl.Split('/');
                        ViewBag.Message = arr[0].ToString();
                        
                        return RedirectToAction(arr[2].ToString(), arr[1].ToString());
                    }
                    return RedirectToAction("Index", "AD_Home");
                }
                else
                {
                    ViewBag.Message = "Incorrect Password.  ";
                }
                
            }
            else
            {
               ViewBag.Message = "Incorrect Email.";
            }

            return View(SAML);
        }

    }
}

BePartner_App_Mid/Views/S_Admin/Regstration_S1.cshtml

@{
    ViewBag.Title = "Regstration_S1";
}

<section class="h-100 bg-dark">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center sa_align-items-center h-100">
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">
                        <div class="col-xl-6 d-none d-xl-block">
                            <img src="~/Img/page_B/img_01.png"
                                 alt="Sample photo" class="img-fluid"
                                 style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;height: 100%;padding:20px;" />
                        </div>
                        <div class="col-xl-6">
                            <center>
                                <img class="img-fluid" src="~/Img/title_logo.png" style="height: 150px; width: 160px; padding: 20px;">
                                <h2> Admin Registration 1/2</h2>
                            </center>

                            <div class="card-body p-md-5 text-black">
                                <form action="" method="post" enctype="multipart/form-data">
                                    <div class="row">
                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" for="form3Example1m">First name:</label>
                                                <span class="text-danger">@Html.ValidationMessage("FirstName")</span>
                                                <input type="text" name="FirstName" value="@(Model!=null? Model.FirstName:"")" placeholder="First name" id="form3Example1m" class="form-control" />
                                            </div>
                                        </div>

                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" for="form3Example1n">Last name:</label>
                                                <span class="text-danger">@Html.ValidationMessage("LastName")</span>
                                                <input type="text" name="LastName" value="@(Model!=null? Model.LastName:"")" placeholder="Last name" id="form3Example1n" class="form-control" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">Email:</label>
                                        <span class="text-danger">@Html.ValidationMessage("Email")</span>
                                        <input type="text" name="Email" value="@(Model!=null? Model.Email:"")" placeholder="example@bepartner.com" id="form3Example8" class="form-control" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">Phone:</label>
                                        <span class="text-danger">@Html.ValidationMessage("Phone")</span>
                                        <input type="text" name="Phone" value="@(Model!=null? Model.Phone:"")" placeholder="01772994093" id="form3Example8" class="form-control" />
                                    </div>

                                    <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">

                                        <label class="form-check-label">Gender:&ensp;  </label>

                                        <div class="form-check form-check-inline mb-0 me-4">
                                            <input class="form-check-input" type="radio" name="Gender" id="maleGender"
                                                   value="Male" />
                                            <label class="form-check-label" for="femaleGender">Male</label>
                                        </div>

                                        <div class="form-check form-check-inline mb-0 me-4">
                                            <input class="form-check-input" type="radio" name="Gender" id="femaleGender"
                                                   value="Female" />
                                            <label class="form-check-label" for="maleGender">Female</label>
                                        </div>

                                        <div class="form-check form-check-inline mb-0">
                                            <input class="form-check-input" type="radio" name="Gender" id="otherGender"
                                                   value="Other" />
                                            <label class="form-check-label" for="otherGender">Other</label>
                                        </div>
                                        <span class="text-danger">@Html.ValidationMessage("Gender")</span>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">NID:</label>
                                        <span class="text-danger">@Html.ValidationMessage("NID")</span>
                                        <input type="text" name="NID" value="@(Model!=null? Model.NID:"")" placeholder="3333 111 222" id="form3Example8" class="form-control" />
                                    </div>


                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">Address:</label>
                                        <span class="text-danger">@Html.ValidationMessage("Address")</span>
                                        <input type="text" name="Address" value="@(Model!=null? Model.Address:"")" placeholder="Address" id="form3Example8" class="form-control" />
                                    </div>
                                    <div class="form-outline mb-4">
                                        <center>

                                            <input type="Submit" value="Continue" onclick="myFunction" class="btn btn-success ad-reg-button">
                                        </center>
                                    </div>
                                </form>

                                <p class="text-center text-muted mt-5 mb-0">
                                    Have already an account? <a href="@Url.Action("login_S","S_Admin")"><u>Login here</u></a>
                                </p>
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


BePartner_App_Mid/Views/S_Admin/Regstration_S2.cshtml

@{
    ViewBag.Title = "Regstration_S2";
}



<section class="h-100 bg-dark">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center sa_align-items-center h-100">
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">

                        <div class="col-xl-6">
                            <center>
                                <img class="img-fluid" src="~/Img/title_logo.png" style="height: 150px; width: 160px; padding: 20px;">
                                <h2> Admin Registration 2/2</h2>
                            </center>

                            <div class="card-body p-md-5 text-black">
                                <form action="" method="post" enctype="multipart/form-data">
                                    <div class="row">
                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" for="form3Example1m">DOB:</label>
                                                <span class="text-danger">@Html.ValidationMessage("DOB")</span>
                                                <input type="date" name="DOB" value="@(Model!=null? Model.DOB.Date:"")" placeholder="Date of brith" id="form3Example1m" class="form-control" />
                                            </div>
                                        </div>

                                        <div class="col-md-6 mb-4">
                                            <div class="form-outline">
                                                <label class="form-label" for="form3Example1n">Security key:</label>
                                                <span class="text-danger">@Html.ValidationMessage("Security_key")</span>
                                                <input type="text" name="Security_key" value="@(Model!=null? Model.Security_key:"")" placeholder="Security key" id="form3Example1n" class="form-control " />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">Password:</label>
                                        <span class="text-danger">@Html.ValidationMessage("Password")</span>
                                        <input type="text" name="Password" value="@(Model!=null? Model.Password:"")" placeholder="Password" id="form3Example8" class="form-control" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example8">Confirm Password:</label>
                                        <span class="text-danger">@Html.ValidationMessage("ConfirmPassword")</span>
                                        <input type="text" name="ConfirmPassword" value="@(Model!=null? Model.ConfirmPassword:"")" placeholder="Confirm Password" id="form3Example8" class="form-control" />
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label for="formFileMultiple" class="form-label">Profile Picture :</label><br />
                                        <input type="file" name="IMG_file">
                                    </div>

                                    <input type="checkbox" value="" id="registerCheck" /> I have read and agree to the terms


                                    <table>
                                        <tr>
                                            <th>
                                                <form action="~/Views/S_Admin/Regstration_S1.cshtml">
                                                    <input type="Submit" value="Previous" class="btn btn-outline-warning ad-reg-button " onclick="href='@Url.Action("Regstration_S1", "S_Admin")'">
                                                </form>
</th>
                                            <th>
                                                <input type="Submit" name="join" value="Join" class="btn btn-success ad-reg-button ">
                                            </th>
                                        </tr>
                                    </table>
                                </form>

                                <p class="text-center text-muted mt-5 mb-0">
                                    Have already an account? <a href="@Url.Action("login_S","S_Admin")"><u>Login here</u></a>
                                </p>

                            </div>
                        </div>

                        <div class="col-xl-6 d-none d-xl-block">
                            <img src="~/Img/page_B/img_01.png"
                                 alt="Sample photo" class="img-fluid"
                                 style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;height: 100%;padding:20px;" />
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BePartner_App_Mid/Views/S_Admin/login_S.cshtml

@{
    ViewBag.Title = "login_S";
}

<style>
    body {
        /*background-color: tan;*/
    }
</style>

<html>
<body>
    
    

    <div class="container ad-continer taransparent">

        <center>
            <img class="img-fluid" src="~/Img/title_logo.png" style="height: 150px; width: 160px; padding: 20px;">
            <h2> Admin Login</h2>
        </center>
        <form action="" method="post">
            <!-- Email input -->
            <div class="form-outline mb-4">
                <!-- <label class="form-label"> Email: </label>-->
                <span class="text-danger">@Html.ValidationMessage("Email")</span>
                <input type="email" name="Email" value="@(Model!=null? Model.Email:"")" placeholder="example@bepartner.com" id="form2Example1" class="form-control taransparent radious" />

            </div>
            <!-- Password input -->
            <div class="form-outline mb-4">
                <!--<label class="form-label"> Password: </label>-->
                <span class="text-danger">@Html.ValidationMessage("Password")</span>

                <input type="password" name="Password" value="@(Model!=null? Model.Password:"")" placeholder="Password" id="form2Example2" class="form-control taransparent radious" />

            </div>
            <!-- 2 column grid layout for inline styling -->
            <div class="row mb-4">
                <div class="col d-flex justify-content-center">
                    <!-- Checkbox -->
                    <div class="form-check">
                        <input class="form-check-input" name="remember" type="checkbox" value="" id="form2Example31" />
                        <label class="form-check-label" for="form2Example31"> Remember me </label>
                    </div>
                </div>

                <div class="col">
                    <!-- Simple link -->
                    <a href="#!"> Forgot password?</a>
                </div>
            </div>
            <!-- Submit button -->
            <input type="submit" value="Login" class="btn btn-outline-success btn-block mb-4 radious">
            <!-- Register buttons -->
            <div class="text-center">
                <p> Not a member? <a href="@Url.Action("Regstration_S1","S_Admin")"> Register </a> </p>

            </div>
        </form>

    </div>
    <center>
        <h5 class="text-danger">@ViewBag.Message</h5>
        <h5 class="text-danger">@ViewBag.dltMessage</h5>
    </center>


</body>
</html>