BePartner_App_Mid/Controllers/InvestorController.cs
using BePartner_App_Mid.EF;
using BePartner_App_Mid.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BePartner_App_Mid.Controllers
{
    public class InvestorController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        // GET: Investor
        [HttpGet]
        public ActionResult Registration()
        {
            if (Session["FirstName"] is string)
            {
                var In = new InvestorPersonal();
                In.FirstName = Session["FirstName"].ToString();
                In.LastName = Session["LastName"].ToString();
                In.Dob = DateTime.Parse(Session["Dob"].ToString());
                In.Address = Session["Address"].ToString();
                In.Phone = Session["Phone"].ToString();
                In.In_Email = Session["Email"].ToString();
                In.Nid = Session["Nid"].ToString();
                In.Gender = Session["Gender"].ToString();
                ViewBag.Message = "data";
                return View(In); 
            }
            else
            {
                ViewBag.Message = "No Data";
                return View();
            }
            //return View();

        }

        [HttpPost]
        public ActionResult Registration(InvestorPersonal In)
        {
            //TempData["Investor"] = In;
            if (ModelState.IsValid)
            {
                Session["FirstName"] = In.FirstName;
                Session["LastName"] = In.LastName;
                Session["Dob"] = In.Dob.Date;
                Session["Address"] = In.Address;
                Session["Phone"] = In.Phone;
                Session["Email"] = In.In_Email;
                Session["Nid"] = In.Nid;
                Session["Gender"] = In.Gender;

                if (In.In_Img != null)
                {
                    string path = Server.MapPath("~/Img");
                    string fileName = Path.GetFileName(In.In_Img.FileName);
                    string ex = Path.GetExtension(In.In_Img.FileName);
                    string fullpath = Path.Combine(path, Session["Email"].ToString()+ex);
                    In.In_Img.SaveAs(fullpath);  //save into img folder


                    // for data base
                    string databaseImgpath = fullpath;
                    Session["IMG_file"] = Session["Email"].ToString() + ex;
                }
                
                
                return RedirectToAction("Registration2");

            }
            else
            {
                //ViewBag.Message = "Not Valid!!";
                
            }

            return View(In);
           
            //return RedirectToAction("Registration2");
            //Registration2(In);
        }

        [HttpGet]
        public ActionResult Registration2()
        {
            
            
            return View();
        }

        [HttpPost]
        public ActionResult Registration2(InvestorProfational In)
        {
            //ViewBag.Message = Session["FirstName"].ToString();
            if (ModelState.IsValid)
            {
                Session["OrgName"] = In.OrgName;
                Session["OrgEstablished"] = In.OrgEstablished.ToString();
                Session["OrgLocation"] = In.OrgLocation;
                Session["OrgEmail"] = In.OrgEmail;
                Session["OrgPhone"] = In.OrgPhone;
                Session["OrgLicense"] = In.OrgLicense;
                Session["Tin"] = In.Tin;
                Session["OrgSite"] = In.OrgSite;

                return RedirectToAction("Registration3");
            }
            else
            {
                ViewBag.Message = "not valid";
            }
            //ViewBag.Message = In.FirstName;
            return View(In);
        }

        [HttpGet]
        public ActionResult Registration3()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registration3(InvestorPassword Pass)
        {
            if (ModelState.IsValid)
            {
                var Par = new InvestorPersonal();
                Par.FirstName = Session["FirstName"].ToString();
                Par.LastName = Session["LastName"].ToString();
                Par.Dob = DateTime.Parse(Session["Dob"].ToString());
                Par.Address = Session["Address"].ToString();
                Par.Phone = Session["Phone"].ToString();
                Par.In_Email = Session["Email"].ToString();
                Par.Nid = Session["Nid"].ToString();
                Par.Gender = Session["Gender"].ToString();
                
                
                var Pro = new InvestorProfational(); 
                Pro.OrgName = Session["OrgName"].ToString();
                Pro.OrgEstablished = DateTime.Parse(Session["OrgEstablished"].ToString());
                Pro.OrgLocation = Session["OrgLocation"].ToString();
                Pro.OrgEmail = Session["OrgEmail"].ToString();
                Pro.OrgPhone = Session["OrgPhone"].ToString();
                Pro.OrgLicense = Session["OrgLicense"].ToString();
                Pro.Tin = Session["Tin"].ToString();
                Pro.OrgSite = Session["OrgSite"].ToString();


                if (this.RegistrationCreate(Par, Pro, Pass))
                {
                    ViewBag.Message = "Data Inserted!!";
                }
                else
                {
                    ViewBag.Message = "Something went wrong!!";
                }
            }
            return View();
        }

        public bool RegistrationCreate(InvestorPersonal Par, InvestorProfational Pro, InvestorPassword Paa)
        {
            
            var investor = new Investor()
            {
                FirstName = Par.FirstName,
                LastName = Par.LastName,
                Dob = Par.Dob,
                Address = Par.Address,
                Phone = Par.Phone,
                In_Email = Par.In_Email,
                Nid = Par.Nid,
                Gender = Par.Gender,
                Img = Session["IMG_file"].ToString(),

                OrgName = Pro.OrgName,
                OrgEstablished = Pro.OrgEstablished,
                OrgLocation = Pro.OrgLocation,
                OrgEmail = Pro.OrgEmail,
                OrgPhone = Pro.OrgPhone,
                OrgLicense = Pro.OrgLicense,
                Tin = Pro.Tin,
                OrgSite = Pro.OrgSite,
                
                Password = Paa.Password,

                EmailValidation = "No",
                Status = "Invalid"
                
            };
            var db = new bePartnerCentralDatabaseEntities2();
            db.Investors.Add(investor);
            try
            {
                db.SaveChanges();
                return true;
            }
            catch
            {
                return false;
            }

        }



        [HttpGet]
        public ActionResult InLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InLogin(InvestorLogin In, string ReturnUrl)
        {
            var db = new bePartnerCentralDatabaseEntities2();
            var investor = (from Id in db.Investors where Id.In_Email.Equals(In.In_Email) select Id).FirstOrDefault();
            if(investor != null)
            {
                if (investor.Password.Equals(In.Password))
                {
                    if (investor.Status.Equals("Invalid"))
                    {
                        ViewBag.Message = "Account is not valid yet.<br>Try again later.";
                    }
                    else
                    {
                        FormsAuthentication.SetAuthCookie(In.In_Email, true);
                        Session.RemoveAll();
                        Session["In_Email"] = In.In_Email;
                        HttpCookie c1 = new HttpCookie("InInfo");
                        c1.Value = investor.In_Email.ToString();
                        c1.Expires = DateTime.Now.AddDays(1);
                        Response.Cookies.Add(c1);
                        if (ReturnUrl != null)
                        {
                            string[] arr = ReturnUrl.Split('/');
                            ViewBag.Message = arr[0].ToString();
                            //return View(In);
                            return RedirectToAction(arr[2].ToString(), arr[1].ToString());
                        }
                        return RedirectToAction("Index", "InHome");
                    }
                    
                }
                else
                {
                    ViewBag.Message = "Incorrect Password. Not " + investor.FirstName + "?<br>Re-enter Email";
                }
                
            }
            else
            {
                ViewBag.Message = "Incorrect Email";
            }
            return View(In);
        }

        

    }
}

BePartner_App_Mid/Views/Investor/InLogin.cshtml

<link href="~/Content/Site.css" rel="stylesheet" type="text/css">
<center>
    <div class="loginbody">
        


        <form action="" method="post">
            <img src="~/Img/title_logo.png" alt="" height="100" width="100">
            <h2 class="text-center">Login</h2>
            <table class="inLogin">



                <tr>
                    <td>
                        <p class="logins">Email:</p>
                    </td>
                </tr>
                <tr>
                    <td>

                        <input type="email" name="In_Email" class="form-control" value="@(Model!=null? Model.In_Email:"")">

                    </td>
                </tr>

                <tr>

                    <td>
                        <p class="logins">Password:</p>
                    </td>
                </tr>
                <tr>
                    <td><input type="password" id="passShow" name="Password" class="form-control" value="@(Model!=null? Model.Password:"")"></td>
                </tr>
                <tr>
                    <td class="text-danger">@Html.Raw(ViewBag.Message)</td>
                </tr>
                <tr>

                    <td><input type="checkbox" onclick="showPass()" name="pwd"> Show Password</td>
                </tr>
                <tr>
                    <td>
                        <input type="checkbox" name="remember"> Remember me.
                    </td>
                </tr>
                <tr>

                    <td><input type="submit" value="Login" name="submit" class="btn btn-success in-login-button">
                </tr>
                <tr>

                    <td><input type="reset" value="Reset" name="Reset" class="btn btn-warning in-login-button"></td>
                </tr>
            </table>
        </form>
    </div>
</center>



@Scripts.Render("~/Content/InValid.js")

BePartner_App_Mid/Views/Investor/Index.cshtml

@{
    ViewBag.Title = "Index";
}

@{ 
    Layout = "~/Views/Shared/_In_Layout.cshtml"; 
}

<h2>Index</h2>

<input type="button" value="Registration" class="btn btn-success" onclick="location.href='@Url.Action("Registration", "Investor")'" />
<input type="button" value="Login" class="btn btn-success" onclick="location.href='@Url.Action("InLogin", "Investor")'" />

BePartner_App_Mid/Views/Investor/Registration.cshtml

@{
    ViewBag.Title = "Registration";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css">

<form action="" method="post" class="in-registration" FormMethod.Post, new { enctype = "multipart/form-data" }>
    <img class="in-reg-img" src="~/Img/title_logo.png" alt="" height="100" width="100">
    <h2>Registration</h2>
    <h2>1/3</h2>

    <label>First Name:</label>
    <input type="text" name="FirstName" value="@(Model!=null? Model.FirstName:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("FirstName")</p>

    <label>Last Name:</label>
    <input type="text" name="LastName" value="@(Model!=null? Model.LastName:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("LastName")</p>

    <label>Gender:</label>
    <br>
    <input type="radio" name="Gender" value="Male" @*class="form-check-input"*@ />
    <label>Male</label>
    <input type="radio" name="Gender" value="Female" @*class="form-check-input"*@ />
    <label>Female</label>
    <input type="radio" name="Gender" value="Other" @*class="form-check-input"*@ />
    <label>Other</label><br>
    <p class="text-danger">@Html.ValidationMessage("Gender")</p>

    <label>Date of birth:</label>
    <input type="date" name="Dob" value="@(Model!=null? Model.Dob.Date:"")" class="form-control">
    <p class="text-danger ">@Html.ValidationMessage("Dob")</p>

    <label>Phone:</label>
    <input type="tel" name="Phone" value="@(Model!=null? Model.Phone:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("Phone")</p>

    <label>Email:</label>
    <input type="email" name="In_Email" value="@(Model!=null? Model.In_Email:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("In_Email")</p>

    <label>NID number:</label>
    <input type="text" name="Nid" value="@(Model!=null? Model.Nid:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("Nid")</p>

    <label>Permanent Address:</label>
    <textarea class="form-control" rows="5" name="Address" placeholder="Enter your full address.." @*value="@(Model!=null? Model.Address:"")"*@>@(Model!=null? Model.Address:"")</textarea>
    <p class="text-danger">@Html.ValidationMessage("Address")</p>

    <label>Profile Picture :</label>
    <input type="File" name="In_Img" value="img"> 
    <p class="text-danger">@Html.ValidationMessage("In_Img")</p>

    <input type="Submit" value="Next" onclick="myFunction" class="btn btn-success in-reg-button">

</form>

<h3 class="text-success">@ViewBag.Message</h3>


BePartner_App_Mid/Views/Investor/Registration2.cshtml

@{
    ViewBag.Title = "Registration2";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css">

<h2>Professional Information</h2>

<form action="" method="post" class="in-registration">
    <img class="in-reg-img" src="~/Img/title_logo.png" alt="" height="100" width="100">
    <h2>Professional Information</h2>
    <h2>2/3</h2>
    <label>Organization's' Name:</label>
    <input type="text" name="OrgName" value="@(Model!=null? Model.OrgName:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgName")</p>

    <label>Established date:</label>
    <input type="date" name="OrgEstablished" value="@(Model!=null? Model.OrgEstablished:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgEstablished")</p>

    <label>Organization's' email:</label>
    <input type="email" name="OrgEmail" value="@(Model!=null? Model.OrgEmail:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgEmail")</p>

    <label>Organization's phone:</label>
    <input type="tel" name="OrgPhone" value="@(Model!=null? Model.OrgPhone:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgPhone")</p>

    <label>Organization license number:</label>
    <input type="text" name="OrgLicense" value="@(Model!=null? Model.OrgLicense:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgLicense")</p>

    <label>Tax identification number:</label>
    <input type="text" name="Tin" value="@(Model!=null? Model.Tin:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("Tin")</p>

    <label>Organization's Site:</label>
    <input type="text" name="OrgSite" value="@(Model!=null? Model.OrgSite:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("OrgSite")</p>

    <label>Organization Address:</label>
    <textarea class="form-control" rows="5" name="OrgLocation" placeholder="Enter your full address.." @*value="@(Model!=null? Model.OrgLocation:"")"*@>@(Model!=null? Model.OrgLocation:"")</textarea>
    <p class="text-danger">@Html.ValidationMessage("OrgLocation")</p>

    <input type="Submit" value="Next" class="btn btn-success in-reg-button">
    <input type="button" value="Previous" class="btn btn-warning in-reg-button" onclick="location.href='@Url.Action("Registration","Investor")'" />



</form>

<h3 class="text-success">@ViewBag.Message</h3>

BePartner_App_Mid/Views/Investor/Registration3.cshtml

@{
    ViewBag.Title = "Registration3";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css">

<h2>Password </h2>

<form action="" method="post" class="in-registration">
    <img class="in-reg-img" src="~/Img/title_logo.png" alt="" height="100" width="100">
    <h2>Almost There</h2>
    <h2>3/3</h2>

    <label> Password:</label>
    <input type="password" name="Password" class="form-control" value="@(Model!=null? Model.Password:"")">
    <p class="text-danger">@Html.ValidationMessage("Password")</p>

    <label>Confirm Password:</label>
    <input type="password" name="ConfirmPassword" value="@(Model!=null? Model.ConfirmPassword:"")" class="form-control">
    <p class="text-danger">@Html.ValidationMessage("ConfirmPassword")</p>

    <input type="Submit" value="Next" class="btn btn-success in-reg-button">
    <input type="button" value="Previous" class="btn btn-warning in-reg-button" onclick="location.href='@Url.Action("Registration2","Investor")'" />

</form>

<h3 class="text-success">@ViewBag.Message</h3>
