BePartner_App_Mid/Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BePartner_App_Mid.Models
{
    public class Report
    {
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "*Invalid Email")]
        [Required(ErrorMessage = "*Enter Email Address")]
        public string Receiver { get; set; }

        [Required(ErrorMessage = "*Subject required")]
        public string Subject { get; set; }


        [Required(ErrorMessage = "*Write some Messege")]
        [StringLength(500, MinimumLength = 25, ErrorMessage = "*Must be more than 25 characters.")]
        public string WMFH { get; set; }


    }
}

BePartner_App_Mid/Controllers/J_EmployeeController.cs
using BePartner_App_Mid.EF;
using BePartner_App_Mid.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BePartner_App_Mid.Controllers
{
    public class J_EmployeeController : Controller
    {
        // GET: J_Employee
        public ActionResult Index()
        {
            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                var ems = (from I in db.Entrepreneurs where I.Status.Equals("Invalid") select I).ToList();
                ViewBag.x = ems.Count();
                return View(ems);
            }
            return RedirectToAction("SignIn", "Employee");
        }

        [HttpPost]
        public ActionResult Delete_Account()
        {
            var email = Session["Email"].ToString();
            var db = new bePartnerCentralDatabaseEntities2();
            var Ed = (from I in db.Employees where I.Emp_Email.Equals(email) select I).FirstOrDefault();

            db.Employees.Remove(Ed);
            Session.Contents.RemoveAll();
            ViewBag.dltMessage = "Account deleted";
            db.SaveChanges();
            return RedirectToAction("SignIn", "Employee");

        }

        [HttpGet]
        public ActionResult AccountInformation()
        {
            if (Session["Email"] != null)
            {
                var email = Session["Email"].ToString();
                var db = new bePartnerCentralDatabaseEntities2();
                var em = (from I in db.Employees where I.Emp_Email.Equals(email) select I).FirstOrDefault();

                ViewBag.EM_Email = email;
                return View(em);


            }
            return RedirectToAction("SignIn", "Employee");
        }

        [HttpPost]
        public ActionResult AccountInformation(EmployeeAccountEdit emreg)
        {
            if (ModelState.IsValid)
            {
                    var email = Session["Email"].ToString();
                    var db = new bePartnerCentralDatabaseEntities2();
                    var Ed = (from I in db.Employees where I.Emp_Email.Equals(email) select I).FirstOrDefault();
                    Ed.FirstName = emreg.FirstName;
                    Ed.LastName = emreg.LastName;
                    Ed.Address = emreg.Address;
                    Ed.Nid = emreg.Nid;
                    Ed.Phone = emreg.Phone;
                    Ed.Password = emreg.Password;
                    Ed.Dob=emreg.Dob;
                    Ed.Security_key=emreg.Security_key;

                db.SaveChanges();

                return View();
            }
            return View();
            //return RedirectToAction("AccountInformation");

        }

        public ActionResult AdminInformation()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                //var ems = (from I in db.Investors where I.Status.Equals("Valid") select I).ToList();
                var ems = db.Admins.ToList();
                ViewBag.x = ems.Count();
                return View(ems);


            }
            return RedirectToAction("SignIn", "Employee");
        }
        public ActionResult EmployeeInformation()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                var ems = (from I in db.Employees where I.Status.Equals("Valid") select I).ToList();
                ViewBag.x = ems.Count();
                //var ems = db.Employees.ToList();
                return View(ems);


            }
            return RedirectToAction("SignIn", "Employee");
        }
        public ActionResult InvestorInformation()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                //var ems = (from I in db.Investors where I.Status.Equals("Valid") select I).ToList();
                var ems = db.Investors.ToList();
                ViewBag.x = ems.Count();
                return View(ems);


            }
            return RedirectToAction("SignIn", "Employee");
        }
        public ActionResult EnterprenurInformation()
        {
            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                var ems = (from I in db.Entrepreneurs where I.Status.Equals("Valid") select I).ToList();
                ViewBag.x =ems.Count();
                return View(ems);


            }
            return RedirectToAction("SignIn", "Employee");
        }
        public ActionResult TaskInformation()
        {
            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                var PT = (from I in db.Tasks where I.Status.Equals("sent") orderby I.TaskId select I).ToList();
                return View(PT);
            }
            return RedirectToAction("SignIn", "Employee");
        }

        public ActionResult Task_Information_done()
        {
            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var db = new bePartnerCentralDatabaseEntities2();
                var PT = (from I in db.Tasks where I.Status.Equals("Done") orderby I.TaskId select I).ToList();
                return View(PT);
            }
            return RedirectToAction("SignIn", "Employee");
        }

        public ActionResult About()
        {
            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();
                return View();
            }
            return RedirectToAction("SignIn", "Employee");
        }

        public ActionResult Blog()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();
                return View();
            }
            return RedirectToAction("SignIn", "Employee");
        }

        public ActionResult Contact()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();
                return View();
            }
            return RedirectToAction("SignIn", "Employee");
        }

        [HttpGet]
        public ActionResult Messege_add()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();
                return View();
            }
            return RedirectToAction("SignIn", "Employee");
        }
        [HttpPost]
        public ActionResult Messege_add(Models.Report AR)
        {
            if (ModelState.IsValid)
            {
                var db = new bePartnerCentralDatabaseEntities2();
                var email = Session["Email"].ToString();
                var EM_report = new EF.Report()
                {
                    sender = email,
                    Receiver = AR.Receiver,
                    Title = AR.Subject,
                    Description = AR.WMFH,
                    Report_Time = DateTime.Now,
                    Status = "Sent"
                };

                db.Reports.Add(EM_report);

                db.SaveChanges();


            }
            return RedirectToAction("Messege_sent");
        }


        public ActionResult Messege_sent()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();


                ViewBag.EM_Email = Session["Email"].ToString();

                var email = Session["Email"].ToString();
                var db = new bePartnerCentralDatabaseEntities2();
                var reps = (from I in db.Reports where I.sender.Equals(email) select I).ToList();

                return View(reps);
                
            }
            return RedirectToAction("SignIn", "Employee");
        }

        public ActionResult Messege_received()
        {

            if (Session["Email"] != null)
            {
                ViewBag.EM_Email = Session["Email"].ToString();

                var email = Session["Email"].ToString();
                var db = new bePartnerCentralDatabaseEntities2();
                var rep = (from I in db.Reports where I.Receiver.Equals(email) select I).ToList();
                
                return View(rep);
               
            }
            return RedirectToAction("SignIn", "Employee");
        }


        public ActionResult Logout()
        {
            Session.Contents.RemoveAll();
            return RedirectToAction("SignIn","Employee");
        }



        // make Employees valid 
        public ActionResult EmployeesValid(String id)
        {
            var db = new bePartnerCentralDatabaseEntities2();
            var Ed = (from I in db.Employees where I.Nid.Equals(id) select I).FirstOrDefault();

            Ed.Status = "Valid";

            try
            {
                db.SaveChanges();
                return RedirectToAction("EmployeeInformation");
            }
            catch
            {
                return View();
            }

        }



BePartner_App_Mid/Views/J_Employee/About.cshtml
<link href="~/Content/em_style.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@{
    Layout = "~/Views/Employee/EM_layout.cshtml";
}

<div class="row">
    <!--Left side-->
    <div class="column1">


        <center>
            <a class="btn btn-success radious" style="width:250px;margin-bottom:10px;margin-top:10px;" href="@Url.Action("Index","J_Employee")">Dashboard</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AccountInformation","J_Employee")">Account Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AdminInformation","J_Employee")">Admin Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EmployeeInformation","J_Employee")"> Employee Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("InvestorInformation","J_Employee")">Investor Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EnterprenurInformation","J_Employee")">Enterprenrur Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("TaskInformation","J_Employee")">Task Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Messege_received","J_Employee")">Messege</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Logout","J_Employee")">Logout</a>

        </center>

    </div>
    <div class="column2">

        <a class="nav-link">
            <h3>Admin</h3>
        </a>

        <p><b>Sazzadul alam shawon</b> <small>  19-39385-1</small></p>
        <img src="~/Img/SUAS.png" width="110" height="120">
        <a href="https://www.facebook.com/sazzadulalamshawonbd/"><img src="~/Img/Facebook.png" width="25" height="25"></a>
        <a href="mailto:sazzad.sua@gmail.com"><img src="~/Img/mail.png" width="25" height="25"></a>


        <p>
            2020-2022 © BEPARTNER <br>
            POWERED BY CODE HUNTER SOFTWARE DEVELOPMENT TEAM.<br>
            AMERICAN INTERNATIONAL UNIVERSITY-BANGLADESH
        </p>

        <p><b>Md. Rifat Hossain</b> <small>  18-38939-3</small></p>
        <img src="~/Img/MRH.png" width="110" height="120">
        <a href="https://www.facebook.com/rrriiifffaaattt/"><img src="~/Img/Facebook.png" width="25" height="25"></a>
        <a href="mailto:sazzad.sua@gmail.com"><img src="~/Img/mail.png" width="25" height="25"></a>
        <p>
            2020-2022 © BEPARTNER <br>
            POWERED BY CODE HUNTER SOFTWARE DEVELOPMENT TEAM.<br>
            AMERICAN INTERNATIONAL UNIVERSITY-BANGLADESH
        </p>


        <p><b>Jannatul Ferdus</b> <small>  19-39371-1</small></p>
        <img src="~/Img/JF.jpg" width="110" height="120">
        <a href="https://www.facebook.com/yesmin.kakon.9/"><img src="~/Img/Facebook.png" width="25" height="25"></a>
        <a href="mailto:jannatul6246ferdus@gmail.com"><img src="~/Img/mail.png" width="25" height="25"></a>
        <p>
            2020-2022 © BEPARTNER <br>
            POWERED BY CODE HUNTER SOFTWARE DEVELOPMENT TEAM.<br>
            AMERICAN INTERNATIONAL UNIVERSITY-BANGLADESH
        </p>


        <p><b>Abdullah al Mahmud</b> <small>  19-39500-1</small></p>
        <img src="~/Img/ALM.jpg" width="110" height="120">
        <a href="https://www.facebook.com/abdullahal.mahmud.5015/"><img src="~/Img/Facebook.png" width="25" height="25"></a>
        <a href="mailto:abdullahalmahmud06337@gmail.com"><img src="~/Img/mail.png" width="25" height="25"></a>
        <p>
            2020-2022 © BEPARTNER <br>
            POWERED BY CODE HUNTER SOFTWARE DEVELOPMENT TEAM.<br>
            AMERICAN INTERNATIONAL UNIVERSITY-BANGLADESH
        </p>

        <hr>

        <a class="nav-link">
            <h3>Employee</h3>
        </a>

        <p><b>Sazzad Hamid</b> <small>  Chief Operating Officer (COO)</small></p>
        <p>
            In the hierarchal set up the Chief Operating Officer holds the second place. In some entities, COO is also called the Chief Operations Director or Chief Operations Officer.  COO acts as focal point to execute business plans. Such person assists the company to work effectively and ensures its financial strength. COO is a leader as well as a supervisor of the company, who confirms that employees are executing the plans of the CEO.
        </p>

        <p><b>Rifat Hossain</b> <small>  Chief Technology Officer (CTO)</small></p>
        <p>
            n the designations in a private company, next comes the Chief Technology Officer. A Chief Technology Officer is a senior executive in the technology department of the company. Such person is responsible for managing and supervising maintenance of technology and development aspects.

            Moreover, the CTO should oversee the technological process, policies, asset maintenance of the company.
        </p>


        <p><b>Dola Shaha</b> <small>  Chief Financial Officer (CFO)</small></p>
        <p>
            In a corporate setup, a Chief Financial Officer or the CFO does financial planning, monitors the cash flow and does other financial activities. Such person is similar to the controller or treasurer of a company. He checks the accuracy of the financial statements and company’s reports.

            CFO also conducts SWOT analysis of the company regularly. SWOT means Strength, Weakness, Opportunities and Threat. Further, the standard duties of a CFO are planning, bookkeeping, accounting, fundraising, budgeting and such other financial/accounting matters.
        </p>


        <p><b>Abdullah al Hafij</b> <small>  Chief Marketing Officer (CMO)</small></p>
        <p>
            A Chief Marketing Officer is a marketing executive engaged in tasks such as managing marketing campaigns, enhancing brand image etc. Further, the Chief Marketing Officer directly operates with marketing and sales department to execute marketing strategies and policies.

            All the managers are required to report to these officers within a private company.
        </p>


        <p><b>Jahangir Alam</b> <small>  Chief Legal Officer (CLO)</small></p>
        <p>
            A Chief Legal Officer acts as a senior legal executive who assists in reducing the legal risks in a company. The main function of a CLO is to advise on regulatory as well as on legal concerns to stakeholders/employees of the company. He reduces the litigation risks.

            The CLO also handles legal matters of a company and acts as a first person for communication with the authorities. There may be more than one manager functioning under the legal departments headed by the CLO.
        </p>

</div>
</div>

BePartner_App_Mid/Views/J_Employee/AccountInformation.cshtml
<link href="~/Content/em_style.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@{
    Layout = "~/Views/Employee/EM_layout.cshtml";
}

<div class="row">
    <!--Left side-->
    <div class="column1">


        <center>
            <a class="btn btn-success radious" style="width:250px;margin-bottom:10px;margin-top:10px;" href="@Url.Action("Index","J_Employee")">Dashboard</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AccountInformation","J_Employee")">Account Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AdminInformation","J_Employee")">Admin Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EmployeeInformation","J_Employee")"> Employee Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("InvestorInformation","J_Employee")">Investor Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EnterprenurInformation","J_Employee")">Enterprenrur Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("TaskInformation","J_Employee")">Task Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Messege_received","J_Employee")">Messege</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Logout","J_Employee")">Logout</a>

        </center>

    </div>

    <!--rigth side-->
    <div class="column2">
        <h2>Account Information</h2>
        <form action="/J_Employee/AccountInformation" method="POST">


            <div class="row">
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1m">First name:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("FirstName")</span>*@
                        <input type="text" name="FirstName" value="@(Model!=null? Model.FirstName:"")" placeholder="First name" id="form3Example1m" class="form-control" />
                    </div>
                </div>

                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1n">Last name:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("LastName")</span>*@
                        <input type="text" name="LastName" placeholder="Enter your last name.." value="@(Model!=null? Model.LastName:"")" class="form-control">
                    </div>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1m">Date of birth:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Dob")</span>*@
                        <input type="date" name="Dob" value="@(Model!=null? Model.Dob:"")" class="form-control">
                    </div>
                </div>

                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1n">NID:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Nid")</span>*@
                        <input type="text" name="Nid" placeholder="Enter your nid number.." value="@(Model!=null? Model.Nid:"")" class="form-control">
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label>Email:</label>
                    <span class="text-danger"> @Html.ValidationMessage("Email")</span>
                    <input type="email" name="Email" placeholder="Enter your full email address.." value="@(Model!=null? Model.Emp_Email:"")" class="form-control" disabled>


                </div>

                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1n">Phone:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Phone")</span>*@
                        <input type="text" name="Phone" placeholder="Enter your phone number.." value="@(Model!=null? Model.Phone:"")" class="form-control">
                    </div>
                </div>
            </div>
            <br />

            <div class="row">

                <div class="col-md-6 mb-4">

                    <div class="form-outline">
                        <label class="form-label" for="form3Example1n">Security key:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Security_key")</span>*@
                        <input type="text" name="Security_key" value="@(Model!=null? Model.Security_key:"")" placeholder="Security key" id="form3Example1n" class="form-control " />

                    </div>
                    <br />
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1m">Password:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Password")</span>*@
                        <input type="password" name="Password" placeholder="********" class="form-control" value="@(Model!=null? Model.Password:"")">
                    </div>

                    <br />
                    <input type="Submit" value="Save" class="btn btn-success">
                </div>

                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="form3Example1m">Parmanent Address:</label>
                        @*<span class="text-danger">@Html.ValidationMessage("Address")</span>*@
                       <input type="text" name="Address" placeholder="Address" class="form-control" value="@(Model!=null? Model.Address:"")">
                    </div>
                </div>


            </div>
 
            <br />
        </form>
            <hr />
            <form action="/J_Employee/Delete_Account" method="post">
                <h3 style="color:red;"> Delete Account* </h3>
                <p>Once you delete your account, there is no going back. Please be certain.</p>
                <input type="Submit" value="Delete" class="btn btn-danger">
            </form>


        
    </div>
</div>






BePartner_App_Mid/Views/J_Employee/AdminInformation.cshtml
<link href="~/Content/em_style.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@{
    Layout = "~/Views/Employee/EM_layout.cshtml";
}

<div class="row">
    <!--Left side-->
    <div class="column1">

        <center>
            <a class="btn btn-success radious" style="width:250px;margin-bottom:10px;margin-top:10px;" href="@Url.Action("Index","J_Employee")">Dashboard</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AccountInformation","J_Employee")">Account Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("AdminInformation","J_Employee")">Admin Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EmployeeInformation","J_Employee")"> Employee Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("InvestorInformation","J_Employee")">Investor Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("EnterprenurInformation","J_Employee")">Enterprenrur Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("TaskInformation","J_Employee")">Task Information</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Messege_received","J_Employee")">Messege</a>

            <a class="btn btn-success radious" style="width: 250px; margin-bottom: 10px" href="@Url.Action("Logout","J_Employee")">Logout</a>

        </center>

    </div>

    <!--rigth side-->
    <div class="column2">
        <h2>Admin Information (@ViewBag.x)</h2>
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>NID</th>
                                <th>Gender</th>
                                <th>Address</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var AD in Model)
                            {
                                <tr>
                                    <td>@AD.FirstName</td>
                                    <td>@AD.LastName</td>
                                    <td>@AD.Ad_Email</td>
                                    <td>@AD.Phone</td>
                                    <td>@AD.Nid</td>
                                    <td>@AD.Gender</td>
                                    <td>@AD.Address</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


